import { useEffect, useState } from 'react';
import { Check, ChevronRight, ShieldCheck } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { interactionApi } from '../../services/api.js';

const initialForm = { sponsorId: '', seniority: 'MID', companyFit: 'MEDIUM', engagement: 'MEDIUM', purchaseIntent: 'RESEARCHING', decisionAuthority: 'USER', interestLevel: 'MEDIUM', nextAction: 'NONE', productTopic: '', budgetKnown: false, followUpRequired: false, notes: '', qualifyAsLead: false };
const options = { seniority: [['EXECUTIVE', 'Executive'], ['SENIOR', 'Senior leader'], ['MID', 'Mid-level'], ['OTHER', 'Other']], companyFit: [['HIGH', 'High fit'], ['MEDIUM', 'Medium fit'], ['LOW', 'Low fit']], engagement: [['HIGH', 'High'], ['MEDIUM', 'Medium'], ['LOW', 'Low']], purchaseIntent: [['0_3_MONTHS', '0-3 months'], ['3_6_MONTHS', '3-6 months'], ['6_12_MONTHS', '6-12 months'], ['RESEARCHING', 'Researching']], decisionAuthority: [['DECISION_MAKER', 'Decision maker'], ['INFLUENCER', 'Influencer'], ['USER', 'User']] };

function ScanInteractionPage() {
  const { attendeeId } = useParams(); const [attendee, setAttendee] = useState(null); const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState(null);
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  useEffect(() => { Promise.resolve().then(() => interactionApi.scan(attendeeId)).then(({ data }) => setAttendee(data.data.attendee)).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to resolve attendee QR code.')).finally(() => setLoading(false)); }, [attendeeId]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const response = await interactionApi.create({ ...form, attendeeId }); setResult(response.data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to record interaction.'); } finally { setSaving(false); } };
  if (loading) return <main className="scan-page"><div className="loading-state">Resolving attendee pass...</div></main>;
  if (error) return <main className="scan-page"><div className="scan-card"><p className="form-error" role="alert">{error}</p></div></main>;
  if (result) return <main className="scan-page"><div className="scan-card result-card"><div className="empty-state-mark"><Check size={22} /></div><p className="eyebrow">Interaction saved</p><h1>{result.lead ? 'Lead qualified' : 'Interaction recorded'}</h1><p>The sponsor interaction was stored securely. Server-calculated score: <strong>{result.score.score}/100 · {result.score.grade}</strong>.</p></div></main>;
  return <main className="scan-page"><div className="scan-card"><p className="eyebrow">Sponsor interaction</p><h1>Capture this conversation.</h1><p className="scan-intro">Review the permitted attendee details, then answer the qualification questions. The final score is calculated by the platform.</p><section className="scan-attendee"><ShieldCheck size={18} /><div><strong>{attendee.firstName} {attendee.lastName}</strong><span>{attendee.jobTitle || 'Role not provided'} · {attendee.company || 'Company not provided'}</span><small>{attendee.leadSharingConsent ? 'Lead sharing consent given' : 'Contact details remain private'}</small></div></section><form onSubmit={submit}><label>Sponsor ID<input required value={form.sponsorId} onChange={(event) => update('sponsorId', event.target.value)} placeholder="Example: SP26-0001" /></label><div className="scan-question-grid">{Object.entries(options).map(([field, choices]) => <label key={field}>{field === 'companyFit' ? 'Company fit' : field === 'purchaseIntent' ? 'Purchase intent' : field === 'decisionAuthority' ? 'Decision authority' : field.charAt(0).toUpperCase() + field.slice(1)}<select value={form[field]} onChange={(event) => update(field, event.target.value)}>{choices.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>)}</div><div className="form-grid"><label>Interest level<select value={form.interestLevel} onChange={(event) => update('interestLevel', event.target.value)}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label><label>Next action<select value={form.nextAction} onChange={(event) => update('nextAction', event.target.value)}><option value="NONE">None</option><option value="MEETING">Meeting</option><option value="SEND_INFORMATION">Send information</option><option value="CALL">Call</option><option value="EMAIL">Email</option></select></label></div><label>Product/topic<input value={form.productTopic} onChange={(event) => update('productTopic', event.target.value)} /></label><label className="check-row"><input type="checkbox" checked={form.budgetKnown} onChange={(event) => update('budgetKnown', event.target.checked)} />Budget is known</label><label className="check-row"><input type="checkbox" checked={form.followUpRequired} onChange={(event) => update('followUpRequired', event.target.checked)} />Follow-up required</label><label className="check-row"><input type="checkbox" checked={form.qualifyAsLead} onChange={(event) => update('qualifyAsLead', event.target.checked)} />Qualify this interaction as a lead</label><label>Notes<textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-action" disabled={saving}>{saving ? 'Saving interaction...' : 'Save interaction'}<ChevronRight size={18} /></button></form></div></main>;
}

export default ScanInteractionPage;