import { useState } from 'react';
import { ChevronRight } from 'lucide-react';
import { attendeeApi } from '../../services/api.js';

const initialRegistration = { firstName: '', lastName: '', email: '', phone: '', jobTitle: '', company: '', industry: '', city: '', country: '', consent: true, leadSharingConsent: false };

function RegistrationPage({ onComplete }) {
  const [form, setForm] = useState(initialRegistration); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); try { const response = await attendeeApi.register({ ...form, email: form.email.trim() }); onComplete(response.data.data.attendee); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to complete registration.'); } finally { setSubmitting(false); } };
  return <div className="workspace"><div className="section-heading"><p className="eyebrow">TEXCELLENCE registration</p><h1>Make your presence count.</h1><p>Tell us about yourself to receive your event pass. No account or password is required.</p></div><form className="registration-form" onSubmit={submit}><div className="form-grid"><label>First name<input required value={form.firstName} onChange={(event) => update('firstName', event.target.value)} /></label><label>Last name<input required value={form.lastName} onChange={(event) => update('lastName', event.target.value)} /></label><label>Email address<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} /></label><label>Role / job title<input value={form.jobTitle} onChange={(event) => update('jobTitle', event.target.value)} /></label><label>Company<input value={form.company} onChange={(event) => update('company', event.target.value)} /></label><label>Industry<input value={form.industry} onChange={(event) => update('industry', event.target.value)} /></label><label>City<input value={form.city} onChange={(event) => update('city', event.target.value)} /></label><label>Country<input value={form.country} onChange={(event) => update('country', event.target.value)} /></label><label>Phone<input value={form.phone} onChange={(event) => update('phone', event.target.value)} /></label></div><label className="check-row"><input type="checkbox" checked={form.consent} onChange={(event) => update('consent', event.target.checked)} />I agree to share my registration details for event operations.</label><label className="check-row"><input type="checkbox" checked={form.leadSharingConsent} onChange={(event) => update('leadSharingConsent', event.target.checked)} />I consent to sponsors receiving permitted profile details after an interaction.</label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-action compact-action" disabled={submitting}>{submitting ? 'Creating your pass...' : 'Create my event pass'}<ChevronRight size={18} /></button></form></div>;
}

export default RegistrationPage;
